<?php
/**
 * Source-derived Phase 7 inventory for every report/aggregate route.
 *
 * This is deliberately independent of WordPress's runtime route registry.
 * `app/Http/Routes/reports.php` contains every declaration; routes.php remains
 * a checked zero-declaration wrapper. Phase 1 contributes the consumer query
 * variants recorded in the smoke manifest.
 */

$route = function (
    $line,
    $verb,
    $path,
    $handler,
    $query,
    $classification,
    $coverage,
    $smokeCases = 1,
    array $variations = []
) {
    return [
        'source_file'         => 'app/Http/Routes/reports.php',
        'source_line'         => (int) $line,
        'verb'                => (string) $verb,
        'path'                => 'reports/' . (string) $path,
        'handler'             => (string) $handler,
        'query'               => (string) $query,
        'classification'      => (string) $classification,
        'coverage'            => (string) $coverage,
        'phase1_smoke_cases'  => (int) $smokeCases,
        'consumer_variations' => $variations,
    ];
};

$groupVariants = ['default/daily', 'monthly', 'yearly'];
$dimensionVariants = ['billing_country', 'shipping_country', 'payment_method'];

return [
    'configured_files' => [
        'app/Http/Routes/reports.php' => 42,
        'app/Http/Routes/routes.php'  => 0,
    ],
    'phase1' => [
        'get_declarations' => 41,
        'get_variations'   => 25,
        'get_smoke_cases'  => 66,
        'known_failure_smoke_cases' => 4,
        'manifest_file'    => 'tests/smoke/routes.manifest.php:683-880',
    ],
    'routes' => [
        $route(27, 'GET', 'overview',
            'OverviewReportController::getOverview',
            'OverviewReportController::getMonthToMonthStats/getCountryWiseStatsImproved app/Http/Controllers/Reports/OverviewReportController.php:47-244',
            'value',
            'reports-overview-baseline-delta',
            1,
            ['resources/admin/Modules/Reports/Overview/Overview.vue:28 no explicit query params']),
        $route(30, 'GET', 'fetch-report-meta',
            'ReportingController::getReportMeta',
            'Order grouped currency/min date app/Http/Controllers/Reports/ReportingController.php:86-124',
            'value',
            'reports-filter-meta',
            2,
            [
                'base ReportFilterModel applicableFilters',
                'resources/admin/Models/Reports/ReportFilterModel.js:74,145 filters/status/types/date/currency/variation/mode',
            ]),
        $route(31, 'GET', 'quick-order-stats',
            'ReportingController::getOrderQuickStats',
            'OrdersReport::getOrderStats app/Modules/ReportingModule/OrdersReport.php:11-132',
            'known_failure',
            'OrdersReport.php:30-40 filters Order.payment_status with succeeded/authorized transaction statuses; executable paid-row KNOWN-FAILURE reports-quick-order-stats-baseline-delta.',
            1,
            ['resources/admin/Bits/Components/Stats/OrderStat/OrderStatBar.vue:171 day_range']),
        $route(32, 'GET', 'report-overview',
            'ReportingController::getReportOverview',
            'OrderResource::reportOverview/orderSummaryByPayment api/Resource/OrderResource.php:1948-2010',
            'value',
            'reports-deprecated-overview-filtered',
            1,
            ['ReportFilterModel params: created_at/payment_status plus controller success statuses']),
        $route(33, 'GET', 'search-repeat-customer',
            'ReportingController::searchRepeatCustomer',
            'CustomerHelper::getRepeatCustomerBySearch app/Helpers/CustomerHelper.php',
            'value',
            'reports-order-aggregates',
            1,
            ['search, order_status, pagination, created_at between']),
        $route(34, 'GET', 'top-products-sold',
            'ReportingController::getTopProductsSold',
            'OrderItemResource::topProductsSold api/Resource/OrderItemResource.php:338-356',
            'skip',
            'Deprecated reader requires a real fluent-products WordPress post through withWhereHas(product); no Product lifecycle fixture is allowed.',
            1,
            ['ReportFilterModel params; created_at/operator/total_sold resource inputs']),
        $route(37, 'GET', 'revenue',
            'RevenueReportController::getRevenue',
            'RevenueReportService::getRevenueData app/Services/Report/RevenueReportService.php:81-169',
            'value',
            'reports-order-aggregates',
            3,
            $groupVariants),
        $route(38, 'GET', 'revenue-by-group',
            'RevenueReportController::getRevenueByGroup',
            'RevenueReportService::revenueByGroup app/Services/Report/RevenueReportService.php:9-79',
            'value',
            'reports-order-aggregates',
            3,
            $dimensionVariants),
        $route(41, 'GET', 'order-value-distribution',
            'OrderReportController::getOrderValueDistribution',
            'OrderReportService::getOrderValueDistribution app/Services/Report/OrderReportService.php:55-73',
            'value',
            'reports-order-aggregates'),
        $route(42, 'GET', 'fetch-new-vs-returning-customer',
            'OrderReportController::getNewVsReturningCustomer',
            'OrderReportService::getNewVsReturningCustomer app/Services/Report/OrderReportService.php:187-244',
            'value',
            'reports-order-aggregates'),
        $route(43, 'GET', 'fetch-order-by-group',
            'OrderReportController::getOrderByGroup',
            'OrderReportService::groupBy app/Services/Report/OrderReportService.php:9-53',
            'value',
            'reports-order-aggregates',
            3,
            $dimensionVariants),
        $route(44, 'GET', 'fetch-report-by-day-and-hour',
            'OrderReportController::getReportByDayAndHour',
            'OrderReportService::getReportByDayAndHour app/Services/Report/OrderReportService.php:246-318',
            'value',
            'reports-order-aggregates'),
        $route(45, 'GET', 'item-count-distribution',
            'OrderReportController::getItemCountDistribution',
            'OrderReportService::getItemCountDistribution app/Services/Report/OrderReportService.php:320-336',
            'value',
            'reports-order-aggregates'),
        $route(46, 'GET', 'order-completion-time',
            'OrderReportController::getOrderCompletionTime',
            'OrderReportService::getOrderCompletionTime app/Services/Report/OrderReportService.php:354-369',
            'value',
            'reports-order-aggregates'),
        $route(47, 'GET', 'order-chart',
            'OrderReportController::getOrderChart',
            'OrderReportService::getOrderLineChart app/Services/Report/OrderReportService.php:75-185',
            'value',
            'reports-order-aggregates',
            3,
            $groupVariants),
        $route(50, 'GET', 'sales-report',
            'DefaultReportController::getSalesReport',
            'DefaultReportService::getAllGraphMetricsSeparate app/Services/Report/DefaultReportService.php:210-361',
            'value',
            'reports-default-sales-aggregates'),
        $route(52, 'GET', 'fetch-top-sold-products',
            'DefaultReportController::getTopSoldProducts',
            'DefaultReportService::fetchTopSoldProducts app/Services/Report/DefaultReportService.php:11-46',
            'value',
            'reports-default-sales-aggregates'),
        $route(53, 'GET', 'fetch-top-sold-variants',
            'DefaultReportController::getTopSoldVariants',
            'DefaultReportService::fetchTopSoldVariants app/Services/Report/DefaultReportService.php:48-91',
            'value',
            'reports-default-sales-aggregates'),
        $route(65, 'GET', 'refund-chart',
            'RefundReportController::getRefundChart',
            'RefundReportService::getRefundData app/Services/Report/RefundReportService.php:54-110',
            'skip',
            'Refund/transaction behavior is explicitly outside Phase 7 safety scope.',
            3,
            $groupVariants),
        $route(66, 'GET', 'weeks-between-refund',
            'RefundReportController::getWeeksBetweenRefund',
            'RefundReportService::weeksBetweenRefund app/Services/Report/RefundReportService.php:129-188',
            'skip',
            'Refund/transaction behavior is explicitly outside Phase 7 safety scope.'),
        $route(67, 'GET', 'refund-data-by-group',
            'RefundReportController::getRefundDataByGroup',
            'RefundReportService::getRefundDataGroupedBy app/Services/Report/RefundReportService.php:9-52',
            'skip',
            'Refund/transaction behavior is explicitly outside Phase 7 safety scope.',
            3,
            $dimensionVariants),
        $route(70, 'GET', 'license-chart',
            'LicenseReportController::getLicenseLineChart',
            'LicenseReportService::getLicenseLineChart app/Services/Report/LicenseReportService.php:43-131',
            'skip',
            'License lifecycle rows are explicitly outside Phase 7 safety scope.'),
        $route(71, 'GET', 'license-pie-chart',
            'LicenseReportController::getLicensePieChart',
            'LicenseReportService::getLicensePieChart app/Services/Report/LicenseReportService.php:133-159',
            'skip',
            'License lifecycle rows are explicitly outside Phase 7 safety scope.'),
        $route(72, 'GET', 'license-summary',
            'LicenseReportController::getLicenseSummary',
            'LicenseReportService::getSummary app/Services/Report/LicenseReportService.php:161-214',
            'skip',
            'License lifecycle rows are explicitly outside Phase 7 safety scope.'),
        $route(75, 'GET', 'dashboard-stats',
            'ReportingController::getDashboardStats',
            'DashBoardReportService::getDashBoardStats app/Services/Report/DashBoardReportService.php:84-164',
            'value',
            'reports-dashboard-range-aggregates'),
        $route(76, 'GET', 'sales-growth-chart',
            'ReportingController::getSalesGrowthChart',
            'DashBoardReportService::getSalesGrowthChart app/Services/Report/DashBoardReportService.php:166-205',
            'value',
            'reports-dashboard-range-aggregates'),
        $route(77, 'GET', 'country-heat-map',
            'ReportingController::getCountryHeatMap',
            'DashBoardReportService::getCountryHeatMap app/Services/Report/DashBoardReportService.php:207-238',
            'value',
            'reports-country-heat-map-baseline-delta'),
        $route(78, 'GET', 'get-recent-orders',
            'ReportingController::getRecentOrders',
            'DashBoardReportService::getRecentOrders app/Services/Report/DashBoardReportService.php:240-265',
            'value',
            'reports-recent-orders'),
        $route(79, 'GET', 'get-recent-activities',
            'ReportingController::getRecentActivities',
            'DashBoardReportService::getRecentActivities app/Services/Report/DashBoardReportService.php:267-300',
            'value',
            'reports-recent-activities',
            2,
            ['default/all', 'resources/admin/Pages/Dashboard/Components/RecentActivity.vue:54 groupKey=daily']),
        $route(80, 'GET', 'get-dashboard-summary',
            'ReportingController::getDashBoardSummary',
            'DashBoardReportService::getSummary app/Services/Report/DashBoardReportService.php:303-353',
            'value',
            'reports-dashboard-summary-baseline-delta'),
        $route(82, 'GET', 'subscription-chart',
            'SubscriptionReportController::getSubscriptionChart',
            'SubscriptionReportService::getChartData app/Services/Report/SubscriptionReportService.php:60-113',
            'skip',
            'Subscription lifecycle rows are explicitly outside Phase 7 safety scope.',
            3,
            $groupVariants),
        $route(83, 'GET', 'daily-signups',
            'SubscriptionReportController::getDailySignups',
            'SubscriptionReportService::getDailySignups app/Services/Report/SubscriptionReportService.php:45-58',
            'skip',
            'Subscription lifecycle rows are explicitly outside Phase 7 safety scope.'),
        $route(84, 'GET', 'retention-chart',
            'SubscriptionReportController::getRetentionChart',
            'SubscriptionReportService::getRetentionChart app/Services/Report/SubscriptionReportService.php:13-43',
            'skip',
            'Subscription lifecycle rows are explicitly outside Phase 7 safety scope.'),
        $route(85, 'GET', 'future-renewals',
            'SubscriptionReportController::getFutureRenewals',
            'SubscriptionReportService future-renewal query app/Services/Report/SubscriptionReportService.php',
            'skip',
            'Subscription lifecycle rows are explicitly outside Phase 7 safety scope.'),
        $route(86, 'GET', 'subscription-retention',
            'SubscriptionReportController::getRetentionData',
            'SubscriptionReportService::getRetentionData app/Services/Report/SubscriptionReportService.php:115-326',
            'skip',
            'Subscription lifecycle rows are explicitly outside Phase 7 safety scope.'),
        $route(87, 'GET', 'subscription-cohorts',
            'SubscriptionReportController::getCohortData',
            'SubscriptionReportService::getCohortData app/Services/Report/SubscriptionReportService.php:328-497',
            'known_failure',
            'Missing fct_retention_snapshots table; tests/FIX-PLAN.md:9.',
            4,
            ['year/subscribers', 'year/mrr', 'month/subscribers', 'month/mrr']),
        $route(88, 'POST', 'retention-snapshots/generate',
            'RetentionSnapshotController::generate',
            'RetentionSnapshotService or Action Scheduler app/Http/Controllers/Reports/RetentionSnapshotController.php:15-61',
            'skip',
            'Unsafe mutating scheduler/snapshot generation route; statically inventoried and never invoked.',
            0),
        $route(89, 'GET', 'retention-snapshots/status',
            'RetentionSnapshotController::checkStatus',
            'Exact WordPress option read app/Http/Controllers/Reports/RetentionSnapshotController.php:66-110',
            'value',
            'reports-retention-status-missing-job',
            2,
            ['manifest nested params.job_id', 'resources/admin/Modules/Reports/Subscription/Cohort.vue:719 polling job_id']),
        $route(92, 'GET', 'product-report',
            'ProductReportController::getProductReport',
            'ProductReportService::getProductReportData app/Services/Report/ProductReportService.php:61-148',
            'skip',
            'Product lifecycle/report rows are explicitly outside Phase 7 safety scope.',
            3,
            $groupVariants),
        $route(93, 'GET', 'product-performance',
            'ProductReportController::getProductPerformance',
            'ProductReportService::getProductTopChart app/Services/Report/ProductReportService.php:9-59',
            'skip',
            'Product lifecycle/report rows are explicitly outside Phase 7 safety scope.',
            2,
            ['base filters', 'resources/admin/Modules/Reports/Product/ProductTopChart.vue:397 pagination/search/order']),
        $route(96, 'GET', 'customer-report',
            'CustomerReportController::index',
            'CustomerReportService::getCustomerReportData app/Services/Report/CustomerReportService.php:9-51',
            'value',
            'reports-order-aggregates',
            3,
            $groupVariants),
        $route(99, 'GET', 'sources',
            'SourceReportController::index',
            'SourceReportService::getSourceReportData app/Services/Report/SourceReportService.php:9-37',
            'value',
            'reports-order-aggregates',
            1,
            ['resources/admin/Modules/Reports/Sources/SourcesReport.vue:76 ReportFilterModel applicableFilters']),
    ],
];
