<?php
/**
 * Phase 18 UUID-bearing customer-portal route inventory.
 *
 * Source locations are executable metadata: the integration runner verifies
 * each route declaration, ownership predicate, denial branch, and first
 * post-guard operation before dispatching any negative request.
 */

$routesFile = 'app/Http/Routes/frontend_routes.php';
$orderController = 'app/Http/Controllers/FrontendControllers/CustomerOrderController.php';
$profileController = 'app/Http/Controllers/FrontendControllers/CustomerProfileController.php';
$subscriptionController = 'app/Http/Controllers/FrontendControllers/CustomerSubscriptionController.php';

$entry = static function (
    $id,
    $verb,
    $path,
    $entity,
    $routeLine,
    $routeNeedle,
    $sourceFile,
    $methodLine,
    $methodNeedle,
    $ownershipLine,
    $ownershipNeedle,
    $denialLine,
    $denialNeedle,
    $postGuardLine,
    $postGuardNeedle,
    array $params = [],
    $publicExempt = false
) use ($routesFile) {
    return [
        'id'                    => $id,
        'verb'                  => $verb,
        'path'                  => $path,
        'entity'                => $entity,
        'route_file'            => $routesFile,
        'route_line'            => $routeLine,
        'route_needle'          => $routeNeedle,
        'source_file'           => $sourceFile,
        'method_line'           => $methodLine,
        'method_needle'         => $methodNeedle,
        'ownership_line'        => $ownershipLine,
        'ownership_needle'      => $ownershipNeedle,
        'denial_line'           => $denialLine,
        'denial_needle'         => $denialNeedle,
        'post_guard_line'       => $postGuardLine,
        'post_guard_needle'     => $postGuardNeedle,
        'params'                => $params,
        'permission_public_exempt' => $publicExempt,
        'coverage'              => 'public-uuid-' . $id,
    ];
};

return [
    // Must equal the number of public_exempt classifications in
    // tests/permissions/routes.manifest.php. Phase 18 (run-integration.php)
    // reconciles that count against BOTH this total and its own literal pin —
    // update all three together. 21→17 when e7b731971 removed the four
    // frontend customer-mutation routes shadowed by the admin customers group
    // ('53:PUT', '56:PUT', '57:POST', '58:DELETE') and their exemptions.
    // 17→20 when the product-review feature added the three public review
    // mutations ('108:POST', '109:PUT', '111:POST') and their exemptions.
    'permission_public_exempt_total' => 20,
    'routes' => [
        $entry(
            'order-detail',
            'GET',
            'customer-profile/orders/%s',
            'order',
            80,
            "orders/{order_uuid}'",
            $orderController,
            115,
            'function orderDetails',
            136,
            "where('customer_id', \$customer->id)",
            148,
            'if (!$order)',
            154,
            'if ($order->type'
        ),
        $entry(
            'order-upgrade-paths',
            'GET',
            'customer-profile/orders/%s/upgrade-paths',
            'order',
            81,
            "orders/{order_uuid}/upgrade-paths'",
            $profileController,
            598,
            'function getUpgradePaths',
            609,
            "where('customer_id', \$currentCustomer->id)",
            612,
            'if (!$order)',
            618,
            "\$variationId = \$request->get('variation_id')",
            ['variation_id' => 1]
        ),
        $entry(
            'transaction-billing-read',
            'GET',
            'customer-profile/orders/%s/billing-address',
            'transaction',
            84,
            "->get('orders/{transaction_uuid}/billing-address'",
            $orderController,
            445,
            'function getTransactionBillingAddress',
            464,
            "where('customer_id', \$customer->id)",
            466,
            'if (empty($order))',
            472,
            "\$order->getMeta('vat_tax_id'"
        ),
        $entry(
            'transaction-billing-write',
            'PUT',
            'customer-profile/orders/%s/billing-address',
            'transaction',
            85,
            "->put('orders/{transaction_uuid}/billing-address'",
            $orderController,
            520,
            'function saveTransactionBillingAddress',
            532,
            "where('customer_id', \$customer->id)",
            534,
            'if (empty($order))',
            551,
            'getValidationRule',
            [
                'address_id' => 0,
                'vat_tax_id' => '',
                'name'       => 'Phase Eighteen',
                'address_1'  => 'Test only',
                'address_2'  => '',
                'city'       => 'Dhaka',
                'state'      => 'C',
                'postcode'   => '1205',
                'country'    => 'BD',
            ],
            true
        ),
        $entry(
            'subscription-detail',
            'GET',
            'customer-profile/subscriptions/%s',
            'subscription',
            90,
            "subscriptions/{subscription_uuid}'",
            $subscriptionController,
            79,
            'function getSubscription',
            97,
            "where('customer_id', \$customer->id)",
            102,
            'if (!$subscription',
            108,
            "\$formattedData = ["
        ),
        $entry(
            'subscription-setup-attempts',
            'GET',
            'customer-profile/subscriptions/%s/setup-intent-attempts',
            'subscription',
            91,
            "subscriptions/{subscription_uuid}/setup-intent-attempts'",
            $subscriptionController,
            593,
            'function getSetupIntentRemainingAttempts',
            610,
            "where('customer_id', \$customer->id)",
            613,
            'if (empty($subscription))',
            626,
            'new SubscriptionsManager'
        ),
        $entry(
            'subscription-update-payment',
            'POST',
            'customer-profile/subscriptions/%s/update-payment-method',
            'subscription',
            92,
            "subscriptions/{subscription_uuid}/update-payment-method'",
            $subscriptionController,
            197,
            'function updatePaymentMethod',
            221,
            "where('customer_id', \$customer->id)",
            224,
            'if (empty($subscription))',
            230,
            'App::gateway()->has',
            ['data' => ['method' => 'phase18-no-gateway']],
            true
        ),
        $entry(
            'subscription-get-plan',
            'POST',
            'customer-profile/subscriptions/%s/get-or-create-plan',
            'subscription',
            93,
            "subscriptions/{subscription_uuid}/get-or-create-plan'",
            $subscriptionController,
            250,
            'function getOrCreatePlan',
            274,
            "where('customer_id', \$customer->id)",
            276,
            'if (empty($subscription))',
            282,
            'APP::gateway()->has',
            ['data' => ['method' => 'phase18-no-gateway', 'reason' => 'guard-test']],
            true
        ),
        $entry(
            'subscription-switch-payment',
            'POST',
            'customer-profile/subscriptions/%s/switch-payment-method',
            'subscription',
            94,
            "subscriptions/{subscription_uuid}/switch-payment-method'",
            $subscriptionController,
            302,
            'function switchPaymentMethod',
            327,
            "where('customer_id', \$customer->id)",
            329,
            'if (empty($subscription))',
            341,
            'App::gateway()->has',
            [
                'data' => [
                    'newPaymentMethod'     => 'phase18-new',
                    'currentPaymentMethod' => 'phase18-old',
                ],
            ],
            true
        ),
        $entry(
            'subscription-confirm-switch',
            'POST',
            'customer-profile/subscriptions/%s/confirm-subscription-switch',
            'subscription',
            95,
            "subscriptions/{subscription_uuid}/confirm-subscription-switch'",
            $subscriptionController,
            363,
            'function confirmSubscriptionSwitch',
            388,
            "where('customer_id', \$customer->id)",
            390,
            'if (empty($subscription))',
            402,
            'APP::gateway()->has',
            [
                'data' => [
                    'newVendorSubscriptionId' => 'phase18-vendor',
                    'method'                  => 'phase18-no-gateway',
                ],
            ],
            true
        ),
        $entry(
            'subscription-cancel',
            'POST',
            'customer-profile/subscriptions/%s/cancel-auto-renew',
            'subscription',
            96,
            "subscriptions/{subscription_uuid}/cancel-auto-renew'",
            $subscriptionController,
            423,
            'function cancelAutoRenew',
            439,
            "where('customer_id', \$customer->id)",
            442,
            'if (empty($subscription))',
            448,
            'cancelRemoteSubscription',
            [],
            true
        ),
        $entry(
            'subscription-early-payment',
            'POST',
            'customer-profile/subscriptions/%s/initiate-early-payment',
            'subscription',
            97,
            "subscriptions/{subscription_uuid}/initiate-early-payment'",
            $subscriptionController,
            465,
            'function initiateEarlyPayment',
            481,
            "where('customer_id', \$customer->id)",
            484,
            'if (!$subscription)',
            490,
            'EarlyPaymentFeature::canPay',
            [],
            true
        ),
        $entry(
            'subscription-pause',
            'POST',
            'customer-profile/subscriptions/%s/pause',
            'subscription',
            98,
            "subscriptions/{subscription_uuid}/pause'",
            $subscriptionController,
            515,
            'function pauseSubscription',
            531,
            "where('customer_id', \$customer->id)",
            534,
            'if (empty($subscription))',
            541,
            'pauseSubscription',
            [],
            true
        ),
        $entry(
            'subscription-resume',
            'POST',
            'customer-profile/subscriptions/%s/resume',
            'subscription',
            99,
            "subscriptions/{subscription_uuid}/resume'",
            $subscriptionController,
            554,
            'function resumeSubscription',
            570,
            "where('customer_id', \$customer->id)",
            573,
            'if (empty($subscription))',
            580,
            'resumeSubscription',
            [],
            true
        ),
    ],
];
