<?php if ( ! defined( 'ABSPATH' ) ) exit;

return [
    "US" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 4,
                'compound' => false,
                'state'    => 'AL',
                'name'     => 'Alabama State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 2,
                'compound' => false,
                'state'    => 'AL',
                'name'     => 'Alabama Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'AL',
                'name'     => 'Alabama Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'AK',
                'name'     => 'Alaska State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'AK',
                'name'     => 'Alaska Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'AK',
                'name'     => 'Alaska Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 5.6,
                'compound' => false,
                'state'    => 'AZ',
                'name'     => 'Arizona State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 3.5,
                'compound' => false,
                'state'    => 'AZ',
                'name'     => 'Arizona Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'AZ',
                'name'     => 'Arizona Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 6.5,
                'compound' => false,
                'state'    => 'AR',
                'name'     => 'Arkansas State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 3,
                'compound' => false,
                'state'    => 'AR',
                'name'     => 'Arkansas Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'AR',
                'name'     => 'Arkansas Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 7.25,
                'compound' => false,
                'state'    => 'CA',
                'name'     => 'California State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 4.25,
                'compound' => false,
                'state'    => 'CA',
                'name'     => 'California Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'CA',
                'name'     => 'California Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 2.9,
                'compound' => false,
                'state'    => 'CO',
                'name'     => 'Colorado State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 1.5,
                'compound' => false,
                'state'    => 'CO',
                'name'     => 'Colorado Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'CO',
                'name'     => 'Colorado Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 6.35,
                'compound' => false,
                'state'    => 'CT',
                'name'     => 'Connecticut State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 3,
                'compound' => false,
                'state'    => 'CT',
                'name'     => 'Connecticut Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'CT',
                'name'     => 'Connecticut Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'DE',
                'name'     => 'Delaware State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'DE',
                'name'     => 'Delaware Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'DE',
                'name'     => 'Delaware Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 6,
                'compound' => false,
                'state'    => 'FL',
                'name'     => 'Florida State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 3,
                'compound' => false,
                'state'    => 'FL',
                'name'     => 'Florida Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'FL',
                'name'     => 'Florida Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 4,
                'compound' => false,
                'state'    => 'GA',
                'name'     => 'Georgia State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 2.5,
                'compound' => false,
                'state'    => 'GA',
                'name'     => 'Georgia Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'GA',
                'name'     => 'Georgia Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 4,
                'compound' => false,
                'state'    => 'HI',
                'name'     => 'Hawaii State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 0.5,
                'compound' => false,
                'state'    => 'HI',
                'name'     => 'Hawaii Wholesale',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0.15,
                'compound' => false,
                'state'    => 'HI',
                'name'     => 'Hawaii Insurance Commissions',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'HI',
                'name'     => 'Hawaii Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 6,
                'compound' => false,
                'state'    => 'ID',
                'name'     => 'Idaho State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 3,
                'compound' => false,
                'state'    => 'ID',
                'name'     => 'Idaho Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'ID',
                'name'     => 'Idaho Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 6.25,
                'compound' => false,
                'state'    => 'IL',
                'name'     => 'Illinois State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 3.5,
                'compound' => false,
                'state'    => 'IL',
                'name'     => 'Illinois Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'IL',
                'name'     => 'Illinois Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 7,
                'compound' => false,
                'state'    => 'IN',
                'name'     => 'Indiana State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 3.5,
                'compound' => false,
                'state'    => 'IN',
                'name'     => 'Indiana Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'IN',
                'name'     => 'Indiana Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 6,
                'compound' => false,
                'state'    => 'IA',
                'name'     => 'Iowa State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 3,
                'compound' => false,
                'state'    => 'IA',
                'name'     => 'Iowa Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'IA',
                'name'     => 'Iowa Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 6.5,
                'compound' => false,
                'state'    => 'KS',
                'name'     => 'Kansas State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 3.25,
                'compound' => false,
                'state'    => 'KS',
                'name'     => 'Kansas Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'KS',
                'name'     => 'Kansas Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 6,
                'compound' => false,
                'state'    => 'KY',
                'name'     => 'Kentucky State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 3,
                'compound' => false,
                'state'    => 'KY',
                'name'     => 'Kentucky Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'KY',
                'name'     => 'Kentucky Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 4.45,
                'compound' => false,
                'state'    => 'LA',
                'name'     => 'Louisiana State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 2.25,
                'compound' => false,
                'state'    => 'LA',
                'name'     => 'Louisiana Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'LA',
                'name'     => 'Louisiana Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 5.5,
                'compound' => false,
                'state'    => 'ME',
                'name'     => 'Maine State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 2.75,
                'compound' => false,
                'state'    => 'ME',
                'name'     => 'Maine Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'ME',
                'name'     => 'Maine Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 6,
                'compound' => false,
                'state'    => 'MD',
                'name'     => 'Maryland State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 3,
                'compound' => false,
                'state'    => 'MD',
                'name'     => 'Maryland Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'MD',
                'name'     => 'Maryland Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 6.25,
                'compound' => false,
                'state'    => 'MA',
                'name'     => 'Massachusetts State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 3,
                'compound' => false,
                'state'    => 'MA',
                'name'     => 'Massachusetts Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'MA',
                'name'     => 'Massachusetts Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 6,
                'compound' => false,
                'state'    => 'MI',
                'name'     => 'Michigan State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 3,
                'compound' => false,
                'state'    => 'MI',
                'name'     => 'Michigan Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'MI',
                'name'     => 'Michigan Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 6.875,
                'compound' => false,
                'state'    => 'MN',
                'name'     => 'Minnesota State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 3.5,
                'compound' => false,
                'state'    => 'MN',
                'name'     => 'Minnesota Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'MN',
                'name'     => 'Minnesota Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 7,
                'compound' => false,
                'state'    => 'MS',
                'name'     => 'Mississippi State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 3.5,
                'compound' => false,
                'state'    => 'MS',
                'name'     => 'Mississippi Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'MS',
                'name'     => 'Mississippi Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 4.225,
                'compound' => false,
                'state'    => 'MO',
                'name'     => 'Missouri State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 2,
                'compound' => false,
                'state'    => 'MO',
                'name'     => 'Missouri Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'MO',
                'name'     => 'Missouri Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'MT',
                'name'     => 'Montana State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'MT',
                'name'     => 'Montana Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'MT',
                'name'     => 'Montana Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 5.5,
                'compound' => false,
                'state'    => 'NE',
                'name'     => 'Nebraska State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 2.75,
                'compound' => false,
                'state'    => 'NE',
                'name'     => 'Nebraska Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'NE',
                'name'     => 'Nebraska Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 6.85,
                'compound' => false,
                'state'    => 'NV',
                'name'     => 'Nevada State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 3.25,
                'compound' => false,
                'state'    => 'NV',
                'name'     => 'Nevada Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'NV',
                'name'     => 'Nevada Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'NH',
                'name'     => 'New Hampshire State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'NH',
                'name'     => 'New Hampshire Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'NH',
                'name'     => 'New Hampshire Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 6.625,
                'compound' => false,
                'state'    => 'NJ',
                'name'     => 'New Jersey State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 3.5,
                'compound' => false,
                'state'    => 'NJ',
                'name'     => 'New Jersey Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'NJ',
                'name'     => 'New Jersey Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 5.125,
                'compound' => false,
                'state'    => 'NM',
                'name'     => 'New Mexico State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 4.875,
                'compound' => false,
                'state'    => 'NM',
                'name'     => 'New Mexico Wholesale',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'NM',
                'name'     => 'New Mexico Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 4,
                'compound' => false,
                'state'    => 'NY',
                'name'     => 'New York State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 2,
                'compound' => false,
                'state'    => 'NY',
                'name'     => 'New York Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'NY',
                'name'     => 'New York Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 4.75,
                'compound' => false,
                'state'    => 'NC',
                'name'     => 'North Carolina State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 2.5,
                'compound' => false,
                'state'    => 'NC',
                'name'     => 'North Carolina Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'NC',
                'name'     => 'North Carolina Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 5,
                'compound' => false,
                'state'    => 'ND',
                'name'     => 'North Dakota State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 2.5,
                'compound' => false,
                'state'    => 'ND',
                'name'     => 'North Dakota Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'ND',
                'name'     => 'North Dakota Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 5.75,
                'compound' => false,
                'state'    => 'OH',
                'name'     => 'Ohio State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 2.75,
                'compound' => false,
                'state'    => 'OH',
                'name'     => 'Ohio Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'OH',
                'name'     => 'Ohio Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 4.5,
                'compound' => false,
                'state'    => 'OK',
                'name'     => 'Oklahoma State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 2.25,
                'compound' => false,
                'state'    => 'OK',
                'name'     => 'Oklahoma Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'OK',
                'name'     => 'Oklahoma Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'OR',
                'name'     => 'Oregon State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'OR',
                'name'     => 'Oregon Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'OR',
                'name'     => 'Oregon Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 6,
                'compound' => false,
                'state'    => 'PA',
                'name'     => 'Pennsylvania State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 3,
                'compound' => false,
                'state'    => 'PA',
                'name'     => 'Pennsylvania Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'PA',
                'name'     => 'Pennsylvania Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 7,
                'compound' => false,
                'state'    => 'RI',
                'name'     => 'Rhode Island State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 3.5,
                'compound' => false,
                'state'    => 'RI',
                'name'     => 'Rhode Island Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'RI',
                'name'     => 'Rhode Island Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 6,
                'compound' => false,
                'state'    => 'SC',
                'name'     => 'South Carolina State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 3,
                'compound' => false,
                'state'    => 'SC',
                'name'     => 'South Carolina Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'SC',
                'name'     => 'South Carolina Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 4.2,
                'compound' => false,
                'state'    => 'SD',
                'name'     => 'South Dakota State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 2.1,
                'compound' => false,
                'state'    => 'SD',
                'name'     => 'South Dakota Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'SD',
                'name'     => 'South Dakota Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 7,
                'compound' => false,
                'state'    => 'TN',
                'name'     => 'Tennessee State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 3.5,
                'compound' => false,
                'state'    => 'TN',
                'name'     => 'Tennessee Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'TN',
                'name'     => 'Tennessee Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 6.25,
                'compound' => false,
                'state'    => 'TX',
                'name'     => 'Texas State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 3,
                'compound' => false,
                'state'    => 'TX',
                'name'     => 'Texas Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 1.5,
                'compound' => false,
                'state'    => 'TX',
                'name'     => 'Texas Reduced 2',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'TX',
                'name'     => 'Texas Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 4.85,
                'compound' => false,
                'state'    => 'UT',
                'name'     => 'Utah State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 2.5,
                'compound' => false,
                'state'    => 'UT',
                'name'     => 'Utah Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'UT',
                'name'     => 'Utah Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 6,
                'compound' => false,
                'state'    => 'VT',
                'name'     => 'Vermont State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 3,
                'compound' => false,
                'state'    => 'VT',
                'name'     => 'Vermont Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'VT',
                'name'     => 'Vermont Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 4.3,
                'compound' => false,
                'state'    => 'VA',
                'name'     => 'Virginia State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 2,
                'compound' => false,
                'state'    => 'VA',
                'name'     => 'Virginia Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'VA',
                'name'     => 'Virginia Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 6.5,
                'compound' => false,
                'state'    => 'WA',
                'name'     => 'Washington State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 3.25,
                'compound' => false,
                'state'    => 'WA',
                'name'     => 'Washington Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'WA',
                'name'     => 'Washington Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 6,
                'compound' => false,
                'state'    => 'WV',
                'name'     => 'West Virginia State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 3,
                'compound' => false,
                'state'    => 'WV',
                'name'     => 'West Virginia Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'WV',
                'name'     => 'West Virginia Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 5,
                'compound' => false,
                'state'    => 'WI',
                'name'     => 'Wisconsin State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 2.5,
                'compound' => false,
                'state'    => 'WI',
                'name'     => 'Wisconsin Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'WI',
                'name'     => 'Wisconsin Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 4,
                'compound' => false,
                'state'    => 'WY',
                'name'     => 'Wyoming State Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 2,
                'compound' => false,
                'state'    => 'WY',
                'name'     => 'Wyoming Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'WY',
                'name'     => 'Wyoming Zero / Exempt',
                'type'     => 'zero',
            ],
            [
                'rate'     => 6,
                'compound' => false,
                'state'    => 'DC',
                'name'     => 'District of Columbia Tax (Standard)',
                'type'     => 'standard',
            ],
            [
                'rate'     => 3,
                'compound' => false,
                'state'    => 'DC',
                'name'     => 'DC Reduced',
                'type'     => 'reduced',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'state'    => 'DC',
                'name'     => 'DC Zero / Exempt',
                'type'     => 'zero',
            ],
        ],
    ],
    "CA" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 5,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'GST',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "MX" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 16,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'IVA',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "GL" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "BR" => [
        "group" => "SA",
        "tax"   => [
            [
                'rate'     => 17,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'ICMS',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "AR" => [
        "group" => "SA",
        "tax"   => [
            [
                'rate'     => 21,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'IVA',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "CL" => [
        "group" => "SA",
        "tax"   => [
            [
                'rate'     => 19,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'IVA',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "CO" => [
        "group" => "SA",
        "tax"   => [
            [
                'rate'     => 19,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'IVA',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "PE" => [
        "group" => "SA",
        "tax"   => [
            [
                'rate'     => 18,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'IGV',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "EC" => [
        "group" => "SA",
        "tax"   => [
            [
                'rate'     => 15,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'IVA',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "UY" => [
        "group" => "SA",
        "tax"   => [
            [
                'rate'     => 22,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'IVA',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "PY" => [
        "group" => "SA",
        "tax"   => [
            [
                'rate'     => 10,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'IVA',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "BO" => [
        "group" => "SA",
        "tax"   => [
            [
                'rate'     => 13,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'IVA',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "VE" => [
        "group" => "SA",
        "tax"   => [
            [
                'rate'     => 16,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'IVA',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "GF" => [
        "group" => "SA",
        "tax"   => [
            [
                'rate'     => 20,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'TVA',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "AG" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 15,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'VAT',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "AI" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "AW" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "BB" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 17.5,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'VAT',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "BL" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "BM" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "BQ" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 8,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'ABB',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "BS" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 10,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'VAT',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "BZ" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 12.5,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'GST',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "CR" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 13,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'IVA',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "CU" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "CW" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 9,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'OB',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "DM" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 15,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'VAT',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "DO" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 18,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'ITBIS',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "FK" => [
        "group" => "SA",
        "tax"   => [
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "GD" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 15,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'VAT',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "GP" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 8.5,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'TVA',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "GS" => [
        "group" => "SA",
        "tax"   => [
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "GT" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 12,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'IVA',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "GY" => [
        "group" => "SA",
        "tax"   => [
            [
                'rate'     => 14,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'VAT',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "HN" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 15,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'ISV',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "HT" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 10,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'TCA',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "JM" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 15,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'GCT',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "KN" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 17,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'VAT',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "KY" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "LC" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 15,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'VAT',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "MF" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "MQ" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 8.5,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'TVA',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "MS" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 10,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'VAT',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "NI" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 15,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'IVA',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "PA" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 7,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'ITBM',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "PM" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "PR" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 11.5,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'SUT',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "SR" => [
        "group" => "SA",
        "tax"   => [
            [
                'rate'     => 10,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'OB',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "SV" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 13,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'IVA',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "SX" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 5,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'OB',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "TC" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "TT" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 12.5,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'VAT',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "UM" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "VC" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 16,
                'compound' => false,
                'type'     => 'standard',
                'name'     => 'VAT',
            ],
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "VG" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
    "VI" => [
        "group" => "NA",
        "tax"   => [
            [
                'rate'     => 0,
                'compound' => false,
                'type'     => 'zero',
            ],
        ],
    ],
];
